
[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = {path = "../../../Fyrox", version = "0.29"}
fyroxed_base = {path = "../../../Fyrox/editor", version = "0.16"}
platformer = { path = "../game" }