
[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
platformer = { path = "../game" }

[dependencies.fyrox ]
git = "https://github.com/FyroxEngine/Fyrox"

[dependencies.fyroxed_base ]
git = "https://github.com/FyroxEngine/Fyrox"
